### ISSUE TITLE
Can't use the add-on since the Anki update

### ISSUE THREAD

**Issue by Nyomaa** [Gustaf-C/anki-chinese-support-3#60] opened 2024-02-12 13:04 UTC
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.19045

Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.taskman", line 104, in wrapped_done
  File "aqt.progress", line 230, in finish
  File "aqt.progress", line 275, in _closeWin
TypeError: isdeleted() argument 1 must be PyQt6.sip.simplewrapper, not None

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Chinese Support 3 ['1752008591', 2023-11-20T13:51, 'None', mod]

===IDs of active AnkiWeb add-ons===
1752008591

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by kieranlblack** [comment] 2024-02-23 03:46
Few quick questions:
- Are you still seeing this issue?
- Does the issue still occur when the addon is disabled?
- Have you tried reinstalling Anki?

**Comment by kieranlblack** [comment] 2024-02-25 05:24
@Nyomaa I was able to reproduce this bug and have opened a PR here https://github.com/ankitects/anki/pull/3029 which should solve it. This is unfortunately not an issue within the chinese support addon and we will likely have to wait until the next release of Anki for it to be fixed.

**Comment by Gustaf-C** [comment] 2024-02-25 09:15
With the race condition in the progress window potentially fixed in the next version of Anki (great job again @kieranlblack!) this will hopefully be resolved with the next Anki release. If you are able to test with the fix it would be nice to know if that resolved the issue.

**Comment by Nyomaa** [comment] 2024-02-26 12:49
Unfortunately it is working but also bugging everytime I use the add-on.
I have copied the bug info 
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.19045

Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.taskman", line 104, in wrapped_done
  File "aqt.progress", line 230, in finish
  File "aqt.progress", line 275, in _closeWin
TypeError: isdeleted() argument 1 must be PyQt6.sip.simplewrapper, not None

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Chinese Support 3 ['1752008591', 2024-02-25T10:37, 'None', mod]

===IDs of active AnkiWeb add-ons===
1752008591

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by kieranlblack** [comment] 2024-02-26 13:54
@Nyomaa yeah, this unfortunately is a bug in Anki itself and while a fix of sorts has been merged, it won't be available until the next release. In the mean time, could you just use the google tts service?

**Comment by CertainJoe** [comment] 2024-03-04 05:30
This happened for me, but I deleted the add-on and redownloaded and it's working now

However it doesn't auto-fill the English section...

**Comment by Gustaf-C** [comment] 2024-03-04 06:51
@CertainJoe 
What is your Anki version?
What is your Chinese support 3 version?
Have you tried disabling all other addons?
Can other fields be autofilled normally?

**Comment by CertainJoe** [comment] 2024-03-04 09:01
@Gustaf-C 
Anki:
Version ⁨23.12.1 (1a1d4d54)⁩
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1

Chinese support 3:
__version__ = '0.17.1'

I don't have other add-ons

Yes all others work normally :)

I have a couple questions--is this the normal pinyin result (example: wǒgānyuànlúnwèi cānghǎiyīsùdepíngfán quèzhǐshìjīnwǎn), where all the words aren't separated? I'm not sure what's normal for pinyin tbh. ~~And is it possible to change the colors? I'm using dark mode and would like to use lighter colors. I think there is but I'm new to it~~

It's not a big deal for me, as the main thing I want is auto-filled pinyin, but I'm not sure what happened for the English to not auto-fill :/

I think the only thing I messed with was Chinese->Speech Engine->I changed the settings a few times

Edit: I found the colors! In styling. Is there a way to dictate what TTS voice is used beyond the options available? And can you dictate the speed somehow?

**Comment by Gustaf-C** [comment] 2024-03-05 02:17
@CertainJoe 
Are you trying to autofill sentences, in that case, no it doesn't work since the English meanings are taken from a dictionary, which obviously does not contain sentence meanings. If you would like to do that there is a google translate addon.

**Comment by CertainJoe** [comment] 2024-03-11 11:24
> @CertainJoe Are you trying to autofill sentences, in that case, no it doesn't work since the English meanings are taken from a dictionary, which obviously does not contain sentence meanings. If you would like to do that there is a google translate addon.

Oh, I see. Thanks :D

**Comment by Gustaf-C** [comment] 2024-04-23 06:31
Closing this for now since it should be fixed in the latest anki release.

**Closed by Gustaf-C** 2024-04-23 06:31 UTC
Labels: bug
