### ISSUE TITLE
Field filling of a card stuck in processing modal screen

### ISSUE THREAD

**Issue by pwoier-sw** [Gustaf-C/anki-chinese-support-3#71] opened 2024-03-07 22:06 UTC
**Describe the bug**
Automatic field filling get stuck when clicking out from the "Expression" field after pressing the 汉字 button.

**To Reproduce**
1. Go to the Browser window
2. Click on any card and then press the 汉字 button
3. Click on the field that has the hanzi filled (in my case, "Expression")
4. Click on the next field, empty; in my case, "Color"
5.  A modal screen opens with the message "Processing" and get stuck there forever.

**Expected behavior**
Automatic field filling of the fields Color and Reading.

**Screenshots**
![image](https://github.com/Gustaf-C/anki-chinese-support-3/assets/31077778/7ad6cec2-5a4a-41e0-9e6b-c9d8df2cce0d)

**Specs (please complete the following information):**
 - OS: Windows 10
 - Anki Version 23.12.1 (1a1d4d54)⁩
- Chinese Support Version v0.17.1

**Additional context**
Every card in this deck has some fields already filled (e.g., Audio, Image_URI etc). I use the add-on to fill the fields: Color (empty) and Reading (already filled, to be overwritten).

**Comment by pwoier-sw** [comment] 2024-03-07 22:39
After creating a new deck with the same note type of the deck previously mentioned, and executing the same steps above on it, the addon worked. Returning to the old deck, the addon worked on it too.

**Comment by Gustaf-C** [comment] 2024-03-08 01:08
Duplicate of #60 and #61

This is an Anki bug which should be fixed in the latest beta.

**Closed as completed by Gustaf-C** 2024-03-08 01:08 UTC
