### ISSUE TITLE
Baidu Speech Engine Processing Error

### ISSUE THREAD

**Issue by tchen9922** [Gustaf-C/anki-chinese-support-3#61] opened 2024-02-14 16:46 UTC
**Describe the bug**
When I use Baidu for the speech feature whilst editing a card, the file will load in, but then a processing window will pop up and won't allow me to close it or Anki at all. I used to use another Chinese add-on, but switched to this one because the speech function worked and I've been trying to add audio to my old cards. However, if I force-quit Anki, then re-open the file plays just fine. 

**To Reproduce**
1. Go to a Chinese card.
2. Click on edit.
3.  Delete the existing sound file, then go to Hanzi and press tab. 

**Expected behavior**
The speech file would be added and there wouldn't be an infinitely processing window pop-up.

**Screenshots**
![image](https://github.com/Gustaf-C/anki-chinese-support-3/assets/160048626/c4e3babe-4b8e-4568-884a-80aa62c6fc9b)

**Specs (please complete the following information):**
 - OS: Windows 10
 - Anki Version ⁨23.12.1 (1a1d4d54)⁩
- Chinese Support Version v0.17.0

Also sorry in advance, I'm not very code savvy or Anki savvy, so I may need some additional information/help.

**Comment by Gustaf-C** [comment] 2024-02-24 05:24
I looked at this quickly, and it seems like Baidu is broken at the moment, maybe they changed their API. I'll see if its possible to fix. In the meantime I suggest using the google speech engine instead.

**Comment by kieranlblack** [comment] 2024-02-24 05:32
For me I don't actually get the infinite loading like described in the issue but it is failing to download the audio from baidu.

**Comment by kieranlblack** [comment] 2024-02-24 05:39
Actually, it only seems to be with specific words, 日语 for example works just fine but 日本 returns 200 OK with no content...

**Comment by kieranlblack** [comment] 2024-02-24 18:29
Super strange bug... baidu's service might be buggy? An hour of digging through pcaps later...

**Comment by tchen9922** [comment] 2024-02-24 23:32
> For me I don't actually get the infinite loading like described in the issue but it is failing to download the audio from baidu.

The audio doesn't load for me if I use Baidu when I'm adding a new Chinese flashcard, I have to use Google. However, if I use Google when I edit old Chinese cards the audio doesn't load, but it loads in Baidu after I force quit. I wonder if this has something to do with the old cards being made on an old Chinese support extension?

**Comment by kieranlblack** [comment] 2024-02-25 03:19
Okay thanks for the extra info. It actually seems like we are dealing with two bugs here then:
- The baidu tts service was not always returning data. I think I fixed this in #66.
- When editing an existing note (not adding a new one), a progress dialog from some subsystem in Anki is getting stuck open. I have been able to reproduce this with your additional information.

**Comment by kieranlblack** [comment] 2024-02-25 03:46
This might be related to #60. I think the error there about being unable to close the open window could be it failing to close this progress window which is getting stuck open.

**Comment by kieranlblack** [comment] 2024-02-25 04:59
There is a race condition in Anki itself. This issue isn't actually totally related to the baidu tts service it just appears here since the baidu service is slow lol. If I artificially increase the time it takes for the plugin to run, we get the same issue with the progress bar stuck open.

If we insert a sandbag here we get the same result too, I think basically what happens is delaying things here causes two operations (maybe an update and a load?) to get bunched together and somehow both are modifying the `ProgressManager` internal state even though everything runs from the main thread 🙀.

https://github.com/ankitects/anki/blob/68b374e65f012f12f6ba266aea293cfaa9616389/qt/aqt/editor.py#L420-L435

**Comment by kieranlblack** [comment] 2024-02-25 06:06
I think we should move any future discussion of the race condition / stuck Processing... window part of this to #60 and keep this issue as conversation about the baidu tts service returning the empty responses.

**Closed** 2024-02-25 09:06 UTC
Labels: bug

**Comment by Gustaf-C** [comment] 2024-02-25 09:09
Thanks for the detective work @kieranlblack! I have merged the fix for baidu and will upload a new version shortly. Since the processing window issue is separate from baidu we'll keep that discussion in #60.
